# Admin Handlers Submodules Package
ADD_PLAN_NAME, ADD_PLAN_DESC, ADD_PLAN_DURATIONS, ADD_DURATION_INPUT = range(4)
PAY_UPI, PAY_QR, PAY_VALIDITY = range(4, 7)
LOG_CHAN_ID = 8
EDIT_PLAN_TITLE, EDIT_PLAN_DESC = range(9, 11)
EDIT_PLAN_LINK = 12
SUB_REVOKE_REASON = 13
SUB_DELETE_REASON = 14
GRANT_USER_ID, GRANT_PLAN, GRANT_DURATION, GRANT_CUSTOM = range(15, 19)
WELCOME_EDIT_TEXT, WELCOME_ADD_BTN, PLAN_ADD_EXT_BTN = range(19, 22)
ADMIN_BROADCAST, ADMIN_ADD_DB = range(22, 24)

ADMIN_MENTION_LINK = "[🦋 ༄Nìśẳntℎ༄ 🦋](https://t.me/aLooser)"
ADMIN_CONTACT_URL = "https://t.me/aLooser"
